[package]
name = "game_kernel"
version = "0.1.0"
authors = ["pac85 <antomani103@gmail.com>"]

[dependencies]
serde = "1.0.72"
serde_derive = "1.0.72"
toml = "0.4"
colored = "1.6"

#multithreading
evmap = "4.0.0"
parking_lot = "0.6.4"
crossbeam-utils = "0.5.0"

vulkano = "0.9.0"
